### ISSUE TITLE
dhclient version 4.3.1?

### ISSUE THREAD

**Issue by jaychris** [jeroenpeeters/docker-network-containers#4]
It looks like the latest version of the container uses dhclient 4.3.1, which doesn't allow the '-H' option:

```
bash-4.3# dhclient -H foo eth1
Internet Systems Consortium DHCP Client 4.3.1
Copyright 2004-2014 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Usage: dhclient [-4|-6] [-SNTPI1dvrxi] [-nw] [-p <port>] [-D LL|LLT]
                [-s server-addr] [-cf config-file]
                [-df duid-file] [-lf lease-file]
                [-pf pid-file] [--no-pid] [-e VAR=val]
                [-sf script-file] [interface]

If you think you have received this message due to a bug rather
than a configuration issue please read the section on submitting
bugs on either our web page at www.isc.org or in the README file
before submitting a bug.  These pages explain the proper
process and the information we find helpful for debugging..

exiting.
```

Not sure if this is a dhclient bug (in which case, can we roll back), or intended behavior going forward (which would be annoying because providing the client hostname via dhclient is pretty standard afaik)

**Comment by jeroenpeeters** [comment]
It seems that I rushed the 'upgrade' to Alpine too quickly. I've rolled back to the CentOs6 base image. All should be fine now. I will try to get it working with Alpine as a base image since it will produce an image 20x smaller than the one based on CentOs. Will do that on the 'alpine' branch.
